//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int customer_id { get; set; }
        public string username { get; set; }
        public string email_address { get; set; }
        public string customer_hashed_password { get; set; }
        public string password_salt { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string address_line_one { get; set; }
        public string address_line_two { get; set; }
        public string postcode { get; set; }
    }
}
