//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int employee_id { get; set; }
        public string employee_first_name { get; set; }
        public string employee_last_name { get; set; }
        public string employee_username { get; set; }
        public string employee_email_address { get; set; }
        public System.DateTime employee_date_of_birth { get; set; }
        public string employee_address_line_one { get; set; }
        public string employee_address_line_two { get; set; }
        public string employee_postcode { get; set; }
        public string employee_hashed_password { get; set; }
        public string employee_password_salt { get; set; }
        public string job_role { get; set; }
        public string employee_sort_code { get; set; }
        public string employee_account_no { get; set; }
        public Nullable<int> employee_shop_id { get; set; }
    
        public virtual SHOP SHOP { get; set; }
    }
}
