'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace api

    Partial Public Class CUSTOMER
        Public Property customer_id As Integer
        Public Property username As String
        Public Property email_address As String
        Public Property customer_hashed_password As String
        Public Property password_salt As String
        Public Property first_name As String
        Public Property last_name As String
        Public Property date_of_birth As Date
        Public Property address_line_one As String
        Public Property address_line_two As String
        Public Property postcode As String
    
    End Class

End Namespace
