'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace api

    Partial Public Class PRCO304_wbutlerEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=PRCO304_wbutlerEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property CUSTOMERS() As DbSet(Of CUSTOMER)
    
    End Class

End Namespace
